CarService/CarService/Models/CarViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CarService.DAL.Entities;

namespace CarService.Models
{
    public class CarViewModel
    {
        public int CarId { get; set; }
        [Required(ErrorMessage = "Значение поля должно присутствовать!")]
        [Display(Name = "Номер")]
        [MinLength(8, ErrorMessage = "Длина номера карты должна быть 8 символов")]
        [MaxLength(8, ErrorMessage = "Длина номера карты не должна быть 8 символов")]
        [RegularExpression(@"[A-Z]{2}[0-9]{4}[A-Z]{2}", ErrorMessage = "Номер должен быть в формате АКТ1234ВК")]
        public string Number { get; set; }

        [Display(Name = "Марка")]
        [Required(ErrorMessage = "Значение поля должно присутствовать!")]
        public string Mark { get; set; }

  
        [Display(Name = "Модель")]
        [Required(ErrorMessage = "Значение поля должно присутствовать!")]
        public string CarModel { get; set; }

        [Required(ErrorMessage = "Значение поля должно присутствовать!")]
        [Display(Name = "Тип кузова")]
        public string Type { get; set; }

        //[Required(ErrorMessage = "Значение поля должно присутствовать!")]
        //public string Color { get; set; }

        [Display(Name = "Объем двигателя, л")]
        [Range(1, 3,
        ErrorMessage = "Значение {0} должно быть между {1} и {2}.")]
        public float EngineVol { get; set; }

        [Display(Name = "Цена за сутки, грн")]
        [Range(typeof(decimal), "100,0", "1000,0", ErrorMessage = "Сумма должна быть больше 100 грн")]      
        //[DisplayFormat(DataFormatString = "{0:F2}", ApplyFormatInEditMode = true)]
        //[DataType(DataType.Currency)]
        //[RegularExpression(@"^\d+(.\d\d)?$", ErrorMessage = "Сумма должна иметь формат 100.01")]
        public decimal PricePerDay { get; set; }

        [Display(Name = "Год выпуска")]
        [Range(2000, 2017,
        ErrorMessage = "Значение {0} должно быть между {1} и текущим годом.")]
        public int ReleaseYear { get; set; }

        [Display(Name = "Пробег")]
        [Range(1, 10000,ErrorMessage = "Значение {0} должно быть между {1} и {2}.")]
        public int MileAge { get; set; }

        [Display(Name = "Количество")]
        [Range(1, 100, ErrorMessage = "Значение {0} должно быть между {1} и {2}.")]
        public int UnitsInStock { get; set; }

        [Display(Name = "Дополнительная информация")]
        public string AdditionalInfo { get; set; }
   
        public byte[] ImageBytes { get; set; }

        public string ImgMimeType { get; set; }

        [Display(Name = "Поставщик")]
        public int ShipperId { get; set; }

        public IEnumerable<ShipperViewModel> Shippers { get; set; }

        //public ICollection<OrderViewModel> Orders { get; set; }

        public ShipperViewModel Shipper { get; set; }
    }
}

CarService/CarService/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CarService.BLL.DTO;
using CarService.BLL.Interfaces;
using CarService.HelpModels;
using CarService.Models;
using Microsoft.AspNet.Identity;


namespace CarService.Controllers
{
    public class CarsController : Controller
    {
        private ICarService _carService;
        private IShipperService _shipperService;

        public CarsController(ICarService service, IShipperService shipperService)
        {
            _carService = service;
            _shipperService = shipperService;
        }

 
        public ActionResult Index()
        {
            var cars = _carService.GetAllCars();
            var model = Mapper.Map<IEnumerable<CarDto>, IEnumerable<CarIndexViewModel>>(cars);
            var modelFilter = new FilterViewModel();
            if (User.IsInRole("User"))
            {
                foreach (var carIndexViewModel in model)
                {
                    if (_carService.Check(User.Identity.GetUserId(), carIndexViewModel.CarId))
                    {
                        carIndexViewModel.Check = true;
                    }
                    if (_carService.CheckLicense(User.Identity.GetUserId()))
                    {
                        modelFilter.License = true;
                    }
                }
            }
         
            modelFilter.Cars = model;
            var listMarks = new List<CheckModel>();            
            ConfigureCheckBoxs(listMarks);
            modelFilter.Marks = listMarks;          
            return View(modelFilter);
        }

        [HttpPost]
        public ActionResult Games(FilterViewModel filters)
        {
            var listMarks = new List<CheckModel>();
         
            SetCheckBoxs(listMarks, filters.MarkList);
            filters.Marks = listMarks;
           
            var filterDto = Mapper.Map<FilterViewModel, FilterDto>(filters);
            filters.Cars =
                  Mapper.Map<List<CarIndexViewModel>>(
                      _carService.GetFiltered(
                          filterDto));
            if (User.IsInRole("User"))
            {
                foreach (var carIndexViewModel in filters.Cars)
                {
                    if (_carService.Check(User.Identity.GetUserId(), carIndexViewModel.CarId))
                    {
                        carIndexViewModel.Check = true;
                    }
                }
            }
            return PartialView("Filtered", filters);
        }

        private void SetCheckBoxs(List<CheckModel> listMarks, string[] marks)
        {
            var marksList = new string[] { "Mazda", "BMW", "Lexus", "Nissan", "CHEVROLET", "HYUNDAI", "HONDA", "MITSUBISHI", "MERCEDES" };
            Array.Sort(marksList);
            foreach (var item in marksList)
            { 
                if (marks != null && marks.Contains(item))
                {
                    listMarks.Add(new CheckModel() {Name =item, Checked = true});
                }
                else
                {
                    listMarks.Add(new CheckModel() {Name = item, Checked = false});
                }
            }
        }

        // GET: Cars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var car = _carService.GetCarById((int)id);
            var model = Mapper.Map<CarDto, CarIndexViewModel>(car);
            if (car == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // GET: Cars/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var model = new CarViewModel();
            var shippers = _shipperService.GetAllShippers();
            var shippersForModel = Mapper.Map<IEnumerable<ShipperDto>, IEnumerable<ShipperViewModel>>(shippers);
            model.Shippers = shippersForModel;
            return View(model);
        }

        // POST: Cars/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(CarViewModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var car =
                   Mapper.Map<CarViewModel, CarDto>(model);
                if (file != null && file.ContentType.StartsWith("image"))
                {
                    _carService.DownloadImage(car, file.ContentType, file.ContentLength);
                    file.InputStream.Read(car.ImageBytes, 0, file.ContentLength);
                }
                _carService.AddGame(car);
                return RedirectToAction("Index");
            }
            var shippers = _shipperService.GetAllShippers();
            var shippersForModel = Mapper.Map<IEnumerable<ShipperDto>, IEnumerable<ShipperViewModel>>(shippers);
            model.Shippers = shippersForModel;
            return View(model);
        }

        // GET: Cars/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var car = _carService.GetCarById((int)id);
            var model = Mapper.Map<CarDto, CarViewModel>(car);
            if (car == null)
            {
                return HttpNotFound();
            }
            var shippers = _shipperService.GetAllShippers();
            var shippersForModel = Mapper.Map<IEnumerable<ShipperDto>, IEnumerable<ShipperViewModel>>(shippers);
            model.Shippers = shippersForModel;
            return View(model);
        }

        // POST: Cars/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CarViewModel model, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var car =
                  Mapper.Map<CarViewModel, CarDto>(model);
                if (file != null && file.ContentType.StartsWith("image"))
                {
                    _carService.DownloadImage(car, file.ContentType, file.ContentLength);
                    file.InputStream.Read(car.ImageBytes, 0, file.ContentLength);
                }
                _carService.EditCar(car);
                return RedirectToAction("Index");
            }
            var shippers = _shipperService.GetAllShippers();
            var shippersForModel = Mapper.Map<IEnumerable<ShipperDto>, IEnumerable<ShipperViewModel>>(shippers);
            model.Shippers = shippersForModel;
            return View(model);
        }

       
        // POST: Cars/Delete/5
        [ActionName("Delete")]        
        public ActionResult DeleteConfirmed(int id)
        {
           _carService.Remove(id);
            return RedirectToAction("Index");
        }

        public void ConfigureCheckBoxs(List<CheckModel> listMarks)
        {
            var marks = new string[] {"Mazda", "BMW", "Lexus", "Nissan", "CHEVROLET", "HYUNDAI", "HONDA", "MITSUBISHI", "MERCEDES" };
            Array.Sort(marks);
            foreach (var item in marks)
            {            
                listMarks.Add(new CheckModel() { Name = item, Checked = false });
            }         
        }

        public FileResult GameImage(int id)
        {
            var imageData = _carService.GetImage(id);
            return File(imageData.Item1, imageData.Item2);
        }
    }
}

CarService/CarService/Views/Cars/Create.cshtml
@model CarService.Models.CarViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создать</h2>


@using (Html.BeginForm("Create", "Cars", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
   
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })      
        <div class="form-group">
            <label class="control-label col-md-2">Изображение</label>
            <div class="col-md-10">
                <input type="file" name="File" class="form-control" accept="image/*" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Mark, new SelectList(
                                    new List<Object>
                                    {
                                        new {value = "1", text = "BMW"},
                                        new {value = "2", text = "CHEVROLET"},
                                        new {value = "3", text = "HONDA"},
                                        new {value = "4", text = "HYUNDAI"},
                                        new {value = "5", text = "Lexus"},
                                        new {value = "6", text = "Mazda"},
                                        new {value = "7", text = "MERCEDES"},
                                        new {value = "8", text = "MITSUBISHI"},
                                        new {value = "9", text = "Nissan"},
                                    },
                                    "value",
                                    "text",
                                    "1"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Type, new SelectList(
                                    new List<Object>
                                    {
                                        new {value = "1", text = "Седан"},
                                        new {value = "2", text = "Внедорожник"}
                                    },
                                    "value",
                                    "text",
                                    "1"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.EngineVol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineVol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineVol, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MileAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MileAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MileAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdditionalInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdditionalInfo, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.ShipperId, "Поставщик", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ShipperId, new SelectList(
       Model.Shippers, "ShipperId", "ShipperName", Model.ShipperId), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipperId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ОК" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    // переопределение валидации на стороне клиента
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
    }

    $.validator.methods.number = function (value, element) {
        return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
    }
    </script>
}



CarService/CarService/Views/Cars/Edit.cshtml
@model CarService.Models.CarViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Редактирование</h2>


@using (Html.BeginForm("Edit", "Cars", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="center">
        <img class="GamePic" src=@Url.Action("GameImage", new {id = Model.CarId}) alt="">
    </div>
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CarId)
        @*<div class="card hovercard">
            <div class="cardheader">
            </div>
            <div class="avatar">*@


        <div class="form-group">
            <label class="control-label col-md-2">Изображение</label>
            <div class="col-md-10">
                <input type="file" name="File" class="form-control" accept="image/*" />
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Mark, new SelectList(
                                    new List<Object>
                                    {
                                        new {value = "1", text = "BMW"},
                                        new {value = "2", text = "CHEVROLET"},
                                        new {value = "3", text = "HONDA"},
                                        new {value = "4", text = "HYUNDAI"},
                                        new {value = "5", text = "Lexus"},
                                        new {value = "6", text = "Mazda"},
                                        new {value = "7", text = "MERCEDES"},
                                        new {value = "8", text = "MITSUBISHI"},
                                        new {value = "9", text = "Nissan"},
                                    },
                                    "value",
                                    "text",
                                    "1"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CarModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CarModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CarModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(model => model.Type, new SelectList(
                                    new List<Object>
                                    {
                                        new {value = "1", text = "Седан"},
                                        new {value = "2", text = "Внедорожник"}
                                    },
                                    "value",
                                    "text",
                                    "1"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.EngineVol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EngineVol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EngineVol, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PricePerDay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerDay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerDay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MileAge, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MileAge, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MileAge, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnitsInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitsInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitsInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdditionalInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdditionalInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdditionalInfo, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.ShipperId, "Поставщик", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ShipperId, new SelectList(
       Model.Shippers, "ShipperId", "ShipperName", Model.ShipperId), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShipperId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ОК" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index", null, new { @class = "btn btn-info no_border" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    // переопределение валидации на стороне клиента
    $.validator.methods.range = function (value, element, param) {
        var globalizedValue = value.replace(",", ".");
        return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
    }

    $.validator.methods.number = function (value, element) {
        return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
    }
    </script>
}